spring:
  application:
      name: POST-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/post_db
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



management:
  health:
   circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
  instances:
    CommentBreaker:
     ratingHotelBreaker:
      registerHealthIndicator: true # Optional, to register a health indicator
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 6s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 5
      slidingWindowType: COUNT_BASED
      permittedNumberOfFailures: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      recordExceptions:
        - java.lang.RuntimeException # Replace with the exceptions you want to record
      ignoreExceptions:
        - java.io.IOException # Replace with the exceptions you want to ignore
      permissions:
        - io.github.resilience4j.example.service.MyService.doSomething # Replace with the method or service you want to protect
